services:
  - type: web
    name: sistem-laporan-medis
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Sistem Laporan Medis
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      # Database connection
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: sistem-laporan-medis-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sistem-laporan-medis-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: sistem-laporan-medis-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: sistem-laporan-medis-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sistem-laporan-medis-db
          property: password
    buildCommand: echo "Build completed in Dockerfile"
    startCommand: /usr/local/bin/startup.sh

  - type: pserv
    name: sistem-laporan-medis-db
    env: mysql
    plan: starter
    databases:
      - name: sistem_laporan_medis
    envVars:
      - key: MYSQL_DATABASE
        value: sistem_laporan_medis
