services:
  - type: web
    name: sistem-laporan-medis
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Sistem Laporan Medis
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      # Database configuration - Set via Render Dashboard Environment Variables
      - key: DB_CONNECTION
        value: mysql
    buildCommand: echo "Build completed in Dockerfile"
    startCommand: /usr/local/bin/startup.sh
